#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_import_dependency_graph.py

Purpose
-------
Generate a raw import dependency graph for a Python codebase.

Output
------
- import_dependency_graph.json
- import_dependency_graph.md

Notes
-----
This script reports only syntactic import relations found in Python source files.
It does not prove runtime execution paths, dynamic imports, or architectural truth.
"""

from __future__ import annotations

import ast
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set


def module_name_from_path(root: Path, path: Path) -> str:
    rel = path.relative_to(root).with_suffix("")
    parts = list(rel.parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def resolve_relative_import(module_name: str, level: int, imported_module: str | None) -> str:
    parts = module_name.split(".")
    if level > len(parts):
        base = []
    else:
        base = parts[:-level]
    if imported_module:
        base.append(imported_module)
    return ".".join([p for p in base if p])


def scan_python_file(path: Path, module_name: str) -> Dict[str, List[str]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    tree = ast.parse(text, filename=str(path))

    imports: Set[str] = set()
    imported_symbols: Set[str] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(alias.name)
        elif isinstance(node, ast.ImportFrom):
            resolved = resolve_relative_import(module_name, node.level, node.module)
            if resolved:
                imports.add(resolved)
            for alias in node.names:
                if alias.name != "*":
                    if resolved:
                        imported_symbols.add(f"{resolved}.{alias.name}")
                    else:
                        imported_symbols.add(alias.name)

    return {
        "imports": sorted(imports),
        "imported_symbols": sorted(imported_symbols),
    }


def build_graph(root: Path) -> dict:
    py_files = sorted(root.rglob("*.py"))

    modules = {}
    reverse_edges = defaultdict(set)

    for path in py_files:
        module_name = module_name_from_path(root, path)
        result = scan_python_file(path, module_name)
        modules[module_name] = {
            "path": str(path.relative_to(root)),
            "imports": result["imports"],
            "imported_symbols": result["imported_symbols"],
        }
        for dep in result["imports"]:
            reverse_edges[dep].add(module_name)

    edges = []
    for module_name, payload in modules.items():
        for dep in payload["imports"]:
            edges.append({
                "from": module_name,
                "to": dep,
                "kind": "direct_import",
            })

    summary = {
        "root": str(root),
        "module_count": len(modules),
        "edge_count": len(edges),
    }

    return {
        "summary": summary,
        "modules": modules,
        "reverse_edges": {k: sorted(v) for k, v in sorted(reverse_edges.items())},
        "edges": edges,
    }


def render_markdown(graph: dict) -> str:
    lines = []
    lines.append("# RAW_IMPORT_DEPENDENCY_GRAPH")
    lines.append("")
    lines.append("This file is autogenerated from Python import syntax.")
    lines.append("")
    lines.append("## Summary")
    lines.append(f"- root: `{graph['summary']['root']}`")
    lines.append(f"- module_count: **{graph['summary']['module_count']}**")
    lines.append(f"- edge_count: **{graph['summary']['edge_count']}**")
    lines.append("")
    lines.append("## Modules")
    for module_name, payload in sorted(graph["modules"].items()):
        lines.append(f"### `{module_name}`")
        lines.append(f"- path: `{payload['path']}`")
        if payload["imports"]:
            lines.append("- imports:")
            for dep in payload["imports"]:
                lines.append(f"  - `{dep}`")
        else:
            lines.append("- imports: none")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: python generate_import_dependency_graph.py <python_root> [<output_dir>]")
        return 1

    root = Path(sys.argv[1]).resolve()
    if not root.exists() or not root.is_dir():
        print(f"Error: root directory does not exist: {root}")
        return 2

    out_dir = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else Path.cwd()
    out_dir.mkdir(parents=True, exist_ok=True)

    graph = build_graph(root)

    json_path = out_dir / "import_dependency_graph.json"
    md_path = out_dir / "import_dependency_graph.md"

    json_path.write_text(json.dumps(graph, indent=2), encoding="utf-8")
    md_path.write_text(render_markdown(graph), encoding="utf-8")

    print(f"Wrote: {json_path}")
    print(f"Wrote: {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
